package com.mjr.extraplanets.world.features;

import java.util.Random;

import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.BlockPos;
import net.minecraft.util.WeightedRandomChestContent;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.minecraftforge.common.ChestGenHooks;

import com.mjr.extraplanets.Config;
import com.mjr.extraplanets.Constants;
import com.mjr.extraplanets.blocks.ExtraPlanets_Blocks;
import com.mjr.mjrlegendslib.util.MessageUtilities;
import com.mjr.mjrlegendslib.util.WorldGenUtilities;

public class WorldGenPurpleHut extends WorldGenerator {

	@Override
	public boolean generate(World world, Random rand, BlockPos position) {
		if (WorldGenUtilities.checkValidSpawn(world, position, 5) == false)
			return false;
		else {
			if (Config.DEBUG_MODE)
				MessageUtilities.debugMessageToLog(Constants.modID, "Spawning Purple Hut at (x, y, z)" + position.toString());
			generateStructure(world, rand, position.up());
			fillChests(world, rand, position.up());
		}
		return true;
	}

	public boolean generateStructure(World world, Random rand, BlockPos position) {
		int x = position.getX();
		int y = position.getY();
		int z = position.getZ();
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 8), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 8), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 8), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 0, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 0, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 0, z + 9), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 0, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 0, z + 9), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 0, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 0, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 7), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 7), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 8), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 8), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 1, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 1), Blocks.oak_stairs.getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 1), Blocks.oak_stairs.getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 1), Blocks.oak_stairs.getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 2), Blocks.oak_stairs.getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 2), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 2), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 2), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 2), Blocks.oak_stairs.getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 3), Blocks.oak_stairs.getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 3), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 3), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 3), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 3), Blocks.oak_stairs.getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 4), Blocks.oak_stairs.getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 4), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 4), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 4), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 4), Blocks.oak_stairs.getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 5), Blocks.oak_stairs.getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 5), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 5), Blocks.planks.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 5), Blocks.wooden_slab.getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 5), Blocks.oak_stairs.getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 6), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 6), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 6), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 7), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 7), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 2, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 1), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 1), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 1), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 2), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 2), Blocks.chest.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 2), Blocks.bed.getStateFromMeta(10), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 3), Blocks.bed.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 2), Blocks.chest.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 2), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 3), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 3), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 4), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 4), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 5), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 5), Blocks.oak_fence.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 3, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 4, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 0), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 1), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 1), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 1), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 2), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 2), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 3), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 3), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 4), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 4), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 5), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 5), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 6), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 6), ExtraPlanets_Blocks.KEPLER22B_MAPLE_LOG.getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 6), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 7), Blocks.oak_stairs.getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 5, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 0), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 1), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 1), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 1), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 1), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 1), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 1), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 2), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 2), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 2), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 2), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 2), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 2), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 3), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 3), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 3), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 3), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 3), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 3), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 4), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 4), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 4), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 4), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 4), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 4), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 5), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 5), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 5), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 5), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 5), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 5), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 6), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 6), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 6), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 6), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 6), Blocks.wooden_slab.getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 6), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 7), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 8), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 0, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 1, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 2, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 3, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 4, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 5, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		world.setBlockState(new BlockPos(x + 6, y + 6, z + 9), Blocks.air.getDefaultState(), 3);
		return true;

	}

	public boolean fillChests(World world, Random rand, BlockPos position) {
		int x = position.getX();
		int y = position.getY();
		int z = position.getZ();
		// Determined if loot should be generated using a 1/2 chance
		int rand = rand.nextInt(10) + 1;
		if (rand < 5) {
			TileEntityChest chest = (TileEntityChest) world.getTileEntity(new BlockPos(x + 2, y + 3, z + 2));

			if (chest != null) {
				for (int i = 0; i < chest.getSizeInventory(); i++) {
					chest.setInventorySlotContents(i, null);
				}

				ChestGenHooks info = ChestGenHooks.getInfo(ChestGenHooks.DUNGEON_CHEST);

				WeightedRandomChestContent.generateChestContents(rand, info.getItems(rand), chest, info.getCount(rand));
			}

			chest = (TileEntityChest) world.getTileEntity(new BlockPos(x + 4, y + 3, z + 2));

			if (chest != null) {
				for (int i = 0; i < chest.getSizeInventory(); i++) {
					chest.setInventorySlotContents(i, null);
				}

				ChestGenHooks info = ChestGenHooks.getInfo(ChestGenHooks.DUNGEON_CHEST);

				WeightedRandomChestContent.generateChestContents(rand, info.getItems(rand), chest, info.getCount(rand));
			}
		}
		return false;
	}
}